# Generated by Django 4.0.2 on 2022-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eroomapp', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
